name: Commit Verification

on: push

# Cancel in-progress runs of the same workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    env:
      PERSON: Bjarne Stroustrup
      ORG_GRADLE_PROJECT_entityToGreet: Bjarne Stroustrup

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v3

    - name: Set up JDK 25
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-read-only: ${{ github.ref != 'refs/heads/master' }}

    - name: Build with Gradle
      run: ./gradlew build --refresh-dependencies

    - name: Run greet task and verify output
      run: |
        ./gradlew greet | tee output.log
        if ! grep -q "$PERSON" output.log; then
          echo "Error: Expected '$PERSON' not found in output"
          cat output.log
          exit 1
        fi
        echo "Success: Output contains '$PERSON'"
